[package]
name = "add_two_numbers"
version = "0.1.0"
edition = "2021"

[lib]
name = "add_two_numbers"
path = "src/lib.rs"

[dependencies]

[[test]]
name = "add_two_numbers_tests"
path = "tests/add_two_numbers.rs"
